blog/urls.py
from django.urls import path 

from blog import views

app_name = 'blog'

urlpatterns  = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
]

blogproject/urls.py
# blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from  django . utils  import  timezone
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    
    """
    Django requires models to inherit models.Model class.
    Category only needs a simple category name name.
    CharField specifies the data type of the category name name, CharField is a character type,
    The max_length parameter of CharField specifies its maximum length, and category names that exceed this length cannot be stored in the database.
    Of course, Django also provides us with many other data types, such as DateTimeField, integer type IntegerField, and so on.
    You can view the documentation for all types built into Django:
    https://docs.djangoproject.com/en/2.2/ref/models/fields/#field-types
    """
    # name = models.CharField(max_length=100)
    name =  models.CharField('Class name', max_length=100 )

    # class Meta:
    #     verbose_name  =  'Classification'
    #     verbose_name_plural = verbose_name

    class Meta:
        verbose_name  =  'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Tag(models.Model): 
    
    """
    Tag is also relatively simple, just like Category.
    Again, we must inherit the models.Model class!
    """
    # name = models.CharField(max_length=100)
    name = models.CharField('label name', max_length=100 )
    
    # class Meta:
    #     verbose_name  =  'Label'
    #     verbose_name_plural = verbose_name

    class Meta:
        verbose_name  =  'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Post(models.Model):
    
    """
    The database table of the article is a little more complicated, mainly involving more fields.
    """

    # Article title
    # title = models.CharField(max_length=70)
    title = models.CharField('title', max_length=70)
    
    # Article body, we used TextField.
    # CharField can be used to store short strings, but it may be a large text for the body of the article, so use TextField to store large text.
    # body = models.TextField()
    body = models.TextField('body')

    # These two columns represent the creation time and last modification time of the article, and the field storing the time is of type DateTimeField.
    # created_time = models.DateTimeField()
    created_time = models.DateTimeField('creation time', default=timezone.now)    
    
    # modified_time = models.DateTimeField()
    modified_time= models.DateTimeField('modified time')
    
    # Article summary, there can be no article summary, but by default CharField requires that we must store data, otherwise it will report an error.
    # Specify the blank=True parameter value of CharField to allow null values.
    # excerpt = models.CharField(max_length=200, blank=True)
    excerpt = models.CharField('Abstract', max_length=200, blank=True)
    
    # This is classification and labeling. The model of classification and labeling has been defined above.
    # Here we associate the database table corresponding to the article with the database table corresponding to the category and label, but the association form is slightly different.
    # We stipulate that one article can only correspond to one category, but there can be multiple articles under one category, so we use ForeignKey, which is a one-to-many association relationship.
    # And since django 2.0, ForeignKey must pass an on_delete parameter to specify the behavior of the associated data when the associated data is deleted,
    # We assume here that when a category is deleted, all articles in that category are also deleted at the same time, so the models.CASCADE parameter is used, which means cascading deletion.
    # For tags, an article can have multiple tags, and there can be multiple articles under the same tag, so we use ManyToManyField to indicate that this is a many-to-many relationship.
    # At the same time, we stipulate that articles can have no tags, so we specify blank=True for tags.
    # If you don't know ForeignKey, ManyToManyField, please see the explanation in the tutorial, or refer to the official documentation:
    # https://docs.djangoproject.com/en/2.2/topics/db/models/#relationships
    
    # category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(Category, verbose_name='category', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='tag', blank=True)
    
    # Article author, here User is imported from django.contrib.auth.models.
    # django.contrib.auth is Django's built-in application, which is specially used to handle the registration and login processes of website users. User is the user model that Django has written for us.
    # Here we associate the article with User through ForeignKey.
    # Because we stipulate that an article can only have one author, and an author may write multiple articles, this is a one-to-many relationship, similar to Category.
   
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='author', on_delete=models.CASCADE)

    # class Meta:
    #     verbose_name  =  'Article'
    #     verbose_name_plural = verbose_name

    class Meta:
        verbose_name  =  'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title  
         
    # Custom get_absolute_url method
    # Remember to import the reverse function from django.urls
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})           

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        super().save(*args, **kwargs) 

blog/views.py
# blog/views.py

import markdown
from django.shortcuts import render, get_object_or_404

from .models import Post


def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    context = {
    	'post_list': post_list
    }
    return render(request, 'blog/index.html', context)
    # return render(request, 'base.html', context)


# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     context = {
#     	'post': post
#     }
#     return render(request, 'blog/detail.html', context)    


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    context = {
        'post': post
    }    
    return render(request, 'blog/detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Black &amp; White</title>

  <!-- meta -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- css -->
  <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

  <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

  <style>
    .codehilite {
      padding: 0;
    }

    /* for block of numbers */
    .hljs-ln-numbers {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;

      text-align: center;
      color: #ccc;
      border-right: 1px solid #CCC;
      vertical-align: top;
      padding-right: 5px;
    }

    .hljs-ln-n {
      width: 30px;
    }

    /* for block of code */
    .hljs-ln .hljs-ln-code {
      padding-left: 10px;
      white-space: pre;
    }
  </style>

  <!-- js -->
  <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
  <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'blog/js/pace.min.js' %}"></script>
  <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
  <header id="site-header">
    <div class="row">
      <div class="col-md-4 col-sm-5 col-xs-8">
        <div class="logo">
          <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
        </div>
      </div><!-- col-md-4 -->
      <div class="col-md-8 col-sm-7 col-xs-4">
        <nav class="main-nav" role="navigation">
          <div class="navbar-header">
            <button type="button" id="trigger-overlay" class="navbar-toggle">
              <span class="ion-navicon"></span>
            </button>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
               <li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
               <li class="cl-effect-11"><a href="full-width.html" data-hover="blog">blog</a></li>
               <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
               <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
             </ul>
          </div><!-- /.navbar-collapse -->
        </nav>
        <div id="header-search-box">
           <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
           <div id="search-form" class="search-form">
             <form role="search" method="get" id="searchform" action="#">
               <input type="search" placeholder="Search" required>
               <button type="submit"><span class="ion-ios-search-strong"></span></button>
             </form>
           </div>
         </div>
       </div><!-- col-md-8 -->
     </div>
   </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">page template</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">Blog of Dreaming People</a></div>

<div class="content-body">
  <div class="container">
    <div class="row">
      <!-- Main -->      
      <main class="col-md-8">
        {% block main %}
        {% endblock main %}
      </main>

      <!-- Aside -->      
      <aside class="col-md-4">

        {% block toc %}
        {% endblock toc %}
        
        <div class="widget widget-recent-posts">
          <h3 class="widget-title">Latest article</h3>
          <ul>
            <li>
              <a href="#">Introduction to Django Blog Development Tutorial: Foreword</a>
            </li>
            <li>
              <a href="#">The Django blog uses Markdown to automatically generate article directories</a>
            </li>
            <li>
              <a href="#">Deploy Django blog</a>
            </li>
          </ul>
        </div>
        <div class="widget widget-archives">
          <h3 class="widget-title">Archive</h3>
          <ul>
            <li>
              <a href="#">May 2017</a>
            </li>
            <li>
              <a href="#">April 2017</a>
            </li>
            <li>
              <a href="#">March 2017</a>
            </li>
          </ul>
        </div>

        <div class="widget widget-category">
          <h3 class="widget-title">Classification</h3>
          <ul>
            <li>
              <a href="#">Django blog tutorial <span class="post-count">(13)</span></a>
            </li>
            <li>
              <a href="#">Python tutorial <span class="post-count">(11)</span></a>
            </li>
            <li>
              <a href="#">Django user authentication <span class="post-count">(8)</span></a>
            </li>
          </ul>
        </div>

        <div class="widget widget-tag-cloud">
           <h3 class="widget-title">Tag cloud</h3>
           <ul>
             <li>
               <a href="#">Django</a>
             </li>
             <li>
               <a href="#">Python</a>
             </li>
             <li>
               <a href="#">Java</a>
             </li>
             <li>
               <a href="#">Notes</a>
             </li>
             <li>
               <a href="#">Documents</a>
             </li>
             <li>
               <a href="#">AngularJS</a>
             </li>
             <li>
               <a href="#">CSS</a>
             </li>
             <li>
               <a href="#">JavaScript</a>
             </li>
             <li>
               <a href="#">Snippet</a>
             </li>
             <li>
               <a href="#">jQuery</a>
             </li>
           </ul>
        </div>
        <div class="rss">
          <a href=""><span class="ion-social-rss-outline"></span> from BASE --RSS subscription</a>
        </div>
      </aside>

    </div>
  </div>
</div>

<!-- Footer -->
<footer id="site-footer">
   <div class="container">
     <div class="row">
       <div class="col-md-12">
         <p class="copyright">&copy 2017-collected from 
          <a href="http://www.cssmoban.com/" target="_blank" title="Template House">Template House</a>
           -Modified by 
           <a href="http://zmrenwu.com/" title="web template" target="_blank">Dreams of Dreamcatchers</a>
         </p>
       </div>
     </div>
   </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
  <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
  <nav>
    <ul>
       <li><a href="index.html">Home</a></li>
       <li><a href="full-width.html">Blog</a></li>
       <li><a href="about.html">About</a></li>
       <li><a href="contact.html">Contact</a></li>
    </ul>
  </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}

  <article class="post post-{{ post.pk }}">
    <!-- Header -->
    <header class="entry-header">
      <!-- Category title -->
      <h1 class="entry-title">{{ post.title }}</h1>

      <div class="entry-meta">
        <!-- Category title -->
        <span class="post-category">
          <a href="#">{{ post.category.name }}</a>
        </span>
        <!-- Created time -->
        <span class="post-date">
          <a href="#">
            <time class="entry-date" 
              datetime="{{ post.created_time }}">
            {{ post.created_time }}</time>
          </a>
        </span>
        <!-- Author -->
        <span class="post-author"><a href="#">{{ post.author }}</a></span>
        <!-- Comments -->
        <span class="comments-link"><a href="#">4 comments</a></span>
        <!-- Views -->
        <span class="views-count"><a href="#">588 Reading</a></span>
      </div>
    </header><!-- ends Header -->

    <!-- Post body -->
    <div class="entry-content clearfix">
      {{ post.body|safe }}
    </div>
  </article>

  <section class="comment-area" id="comment-area">
    <hr>
    <h3>
    Post a comment </ h3>
    <form action="#" method="post" class="comment-form">
      <div class="row">
        <div class="col-md-4">
          <label for="id_name">Name:</label>
          <input type="text" id="id_name" name="name" required>
        </div>
        <div class="col-md-4">
          <label for="id_email">Mailbox:</label>
          <input type="email" id="id_email" name="email" required>
        </div>
        <div class="col-md-4">
          <label for="id_url">URL:</label>
          <input type="text" id="id_url" name="url">
        </div>
        <div class="col-md-12">
          <label for="id_comment">Comment:</label>
          <textarea name="comment" id="id_comment" required></textarea>
          <button type="submit" class="comment-btn">Post</button>
        </div>
      </div>
      <!-- row -->
    </form>
    <div class="comment-list-panel">
      <h3>----Comment list of <span> 4 </span> comments </h3>
      <ul class="comment-list list-unstyled">
        <li class="comment-item">
          <span class =" nickname "> dream chasers </ span>
          <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">March 12, 2017 14:56</time>
          <div class="text">
            The point of view of the article is reasonable and in line with human nature. This is really written to express the point of view, not to cater to the fans of certain celebrities. I think if Qiong Yao is an ex-wife, and after having three children, she was dug into the corner by an unknown woman, I don't believe anyone would say that the woman is pursuing true love, and that the woman who sympathizes with Qiong Yao for scolding Xiaosan is weak.
          </div>
        </li>
        <li class="comment-item">
          <span class="nickname">zmrenwu</span>
          <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">March 11, 2017 23:56</time>
          <div class="text">
            Instinct may break through the pattern, but sometimes the pattern also restrains instinct.
          </div>
        </li>
        <li class="comment-item">
          <span class =" nickname "> Batman </ span>
          <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">March 9, 2017 8:56</time>
          <div class="text">
            In fact, truth generally belongs to the silent majority. Those radical views can only attract those who are equally radical. In the past few years, Qiong Yao sued Yu for plagiarism. Everyone said that they were very popular, indicating that the audience who eat melons are just talking about things, not prejudicing Qiong Yao.
          </div>
        </li>
        <li class="comment-item">
          <span class =" nickname "> Changjiang Seventh </ span>
          <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">February 12, 2017 12:56</time>
          <div class="text">
            I really like the point of view! It’s just that it’s clear, and a little three, four, a mess, a mess, it’s almost troublesome.
          </div>
        </li>
      </ul>
    </div>
  </section>

{% endblock main %}

{% block toc %}
  <div class="widget widget-content">
    <h3 class="widget-title"> from DETAIL - Article directory </h3>
    <ul>
      <li>
        <a href="#"> Tutorial characteristics </a>
      </li>
      <li>
        <a href="#"> who fit this tutorial </a>
      </li>
      <li>
        <a href="#"> Online Preview </a>
      </li>
      <li>
        <a href="#"> Resource List </a>
      </li>
      <li>
        <a href="#"> Getting Help </a>
      </li>
    </ul>
  </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}

  {% for post in post_list %}
    <article class="post post-{{ post.pk }}">
      <!-- Header -->
      <header class="entry-header">
        <!-- Post title -->
        <h1 class="entry-title">
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>

        <!-- Category title, Created time, Author, Comments and Views -->
        <div class="entry-meta">
          <!-- Category title -->
          <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
          <!-- Created time -->
          <span class="post-date">
            <a href="#">
              <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
            </a>
          </span>
          <!-- Author -->
          <span class="post-author"><a href="#">{{ post.author }}</a></span>
          <!-- Comments -->
          <span class="comments-link"><a href="#">4 comments</a></span>
          <!-- Views -->
          <span class="views-count"><a href="#">588 Reading</a></span>
        </div>
      </header><!-- ends Header -->
      
      <!-- Excerpt -->
      <div class="entry-content clearfix">
        <p>{{ post.excerpt }}</p>
        <div class="read-more cl-effect-14">
          <a href="{{ post.get_absolute_url }}" class="more-link">Continue reading <span class="meta-nav">→</span></a>
        </div>
      </div>
    </article><!-- ends Excerpt -->
  {% empty %}
    <div class="no-post">There are no posts yet! </div >
  {% endfor %}

  <!-- Pagination -->
  <div class="pagination">
    <ul>
      <li><a href="">1</a></li>
      <li><a href="">...</a></li>
      <li><a href="">4</a></li>
      <li><a href="">5</a></li>
      <li class="current"><a href="">6</a></li>
      <li><a href="">7</a></li>
      <li><a href="">8</a></li>
      <li><a href="">...</a></li>
      <li><a href="">11</a></li>
    </ul>
  </div>


{% endblock main %}